# -*- coding: utf-8 -*-
SITE_TITLE = 'Josh\'s Blog'
SITE_GREETING = 'Why hello there'
SITE_TAGLINE = ''
SITE_URL = '/'
POSTS_PER_PAGE = 14
ADMIN_USERNAME = 'admin'
ADMIN_PASSWORD = 'pbkdf2:sha1:1000$5sYtpSgp$68c1c417e7003dd2fe2f53428c6463f26fc39749'
ANALYTICS_ID = ''
SQLALCHEMY_DATABASE_URI = 'sqlite:///bragart.db'
GITHUB_USERNAME = ''
LINKEDIN_PROFILE_URL = ''
TWITTER_HANDLE = 'biorice'
FACEBOOK_PROFILE_URL = ''
CONTACT_EMAIL = ''
FONT_NAME = 'Source+Sans+Pro'
SECRET_KEY = '2I3VGMWBWF2Q43XJMJ65KUHDA7Z6HZU5B6LWWADS575FMJJO4W7Q===='
USE_ADDTOANY = True
USE_SUBTOME = False
