# -*- coding: utf-8 -*-
SITE_TITLE = ''
SITE_GREETING = 'Why hello there'
SITE_TAGLINE = ''
SITE_URL = '/'
POSTS_PER_PAGE = 14
ADMIN_USERNAME = 'admin'
ADMIN_PASSWORD = 'pbkdf2:sha1:1000$iN5249Pa$302b845cbe52aa033b7fcf27c4ca90dc82455d40'
ANALYTICS_ID = ''
SQLALCHEMY_DATABASE_URI = 'sqlite:///bragart.db'
GITHUB_USERNAME = ''
LINKEDIN_PROFILE_URL = ''
CONTACT_EMAIL = ''
FONT_NAME = 'Source+Sans+Pro'
SECRET_KEY = 'GCAMHISOFLHVC4FXUOZKRDN2Q4SF7P4KOMNKOPP4GQKNWNC2MSCA===='
USE_ADDTOANY = True
USE_SUBTOME = False
