# -*- coding: utf-8 -*-
POSTS_PER_PAGE = 5
ADMIN_USERNAME = 'admin'
ADMIN_PASSWORD = 'pbkdf2:sha1:1000$yMggs6Oy$bccdb3a48655f0282d146671c91c8b4f04e98a53'
ANALYTICS_ID = ''
SQLALCHEMY_DATABASE_URI = 'sqlite:///bragart.db'
GITHUB_USERNAME = ''
CONTACT_EMAIL = ''
SITE_TITLE = ''
SITE_TAGLINE = ''
SITE_URL = '/'
FONT_NAME = 'Source+Sans+Pro'
SECRET_KEY = 'PR6NDTRLHVSEO6W4FHDCPTOWWQDQYJ5D4PXE3CBZCTW2C4TSS3OA===='
USE_ADDTOANY = True
USE_SUBTOME = False
